server:
  port: 8082
#  context-path: /test
#name: abc
#age: 18
#content: "name: ${name},age: ${age}"
#user:
#  name: abc
#  age: 18
# active: dev
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver


