server:
  port: 8080
  context-path: /demo

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/girl?useSSL=true
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#      cache: false
#      mode: HTML5
#      encoding: utf-8
#      content-type: text/html
mybatis:
  mapperLocations: classpath:mapper/*.xml



